joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 10
 
position_controller_snake:
  type: "position_controllers/JointPositionController"
  joint: snake_joint
 
position_controller_scorpion:
  type: "position_controllers/JointPositionController"
  joint: scorpion_joint